### PR TITLE
Added delete messages feature to admin

### PR DESCRIPTION
**Pull request by spoodermao**
added a commands for admins to delete a number of commands, this number is given as an argument to the command

### CODE REVIEW

**Review by youben11 — COMMENTED** [review]
This project is just a template for other discordjs bots to start from, we don't want to add commands or features, even if they might be useful. Adding commands should go into actual bot projects.
Wdyt @akram09

**Comment by spoodermao** [comment]
> 
Since it's purpose is not clear, i thought of adding commands that I think are necessary for an admin to have.

**Review by akram09 — COMMENTED** [review]
I do agree with what @youben11 said, we don't want to add commands here to keep this project simple

**Comment by akram09** [comment]
Although I thank you for the contribution @Abdelmaoo, please though send me your email in discord

**Pull request closed without merging**
